[package]
name = "rengine"
version = "0.2.0"
edition = "2024"

[dependencies]
once_cell = "1.21.3"
uuid =  { version = "1.0", features = ["v4", "serde"] }
sdl2 = "0.36" # or latest
crossbeam = "0.8.4"
serial_test = "2.0"
